#!/usr/bin/env bash

curl -O https://downloads.cursor.com/production/96e5b01ca25f8fbd4c4c10bc69b15f6228c80771/linux/x64/Cursor-0.50.5-x86_64.AppImage
chmod +x ./Cursor-0.50.5-x86_64.AppImage

./Cursor-0.50.5-x86_64.AppImage

