#!/usr/bin/env bash

# lua btw
cargo install stylua

# luarocks
pushd /tmp/luarocks-3.11.0
(
    wget --output-document /tmp/luarocks.tar.gz https://luarocks.org/releases/luarocks-3.11.0.tar.gz
    tar zxpf /tmp/luarocks.tar.gz -C /tmp
    cd /tmp/luarocks-3.11.0 
    ./configure --with-lua-bin=/usr/bin
    sudo make
    sudo make install
)
popd


