#!/usr/bin/env bash

rm -rf $HOME/personal/neovim
mkdir -p $HOME/personal
git clone --branch v0.10.2 https://github.com/neovim/neovim.git $HOME/personal/neovim
brew install ninja cmake gettext curl

cd $HOME/personal/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
