#!/usr/bin/env bash

sudo pacman -S --no-confirm zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Direnv checks sets folder-level env variables via .envrc
sudo pacman -S direnv
sudo pacman -S --noconfirm wl-clipboard
