#!/usr/bin/env bash

sudo apt install -y zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Direnv checks sets folder-level env variables via .envrc
sudo apt install -y direnv
