#!/usr/bin/env bash

sudo apt -y update
sudo apt -y install git ripgrep pavucontrol xclip jq tldr shutter python3-pip htop

git clone git@github.com:junegunn/fzf.git $HOME/projects/fzf
$HOME/projects/fzf/install
